#
# HeadsPlaceFix v1.0
#
# github.com/Klogakevin201
#

settings:
  #
  # Включить ли подтверждение?
  #
  # Если включено, при первой
  # Попытке, голова не поставится
  # Но при второй получится
  #
  confirm: true